# Generated by Django 5.2.17 on 2026-10-03 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('ARMS', 'Arms'), ('CORE', 'Core'), ('FULL_BODY', 'Full body'), ('CARDIO', 'Cardio')], max_length=20)),
                ('exercise_type', models.CharField(choices=[('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexibility'), ('RECOVERY', 'Recovery')], max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('calories_per_minute', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workout_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-workout_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('target_sets', models.PositiveIntegerField()),
                ('target_reps', models.PositiveIntegerField()),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_details', to='workouts.exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['order_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_sets', models.PositiveIntegerField()),
                ('actual_reps', models.PositiveIntegerField()),
                ('actual_weight', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout_plan_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='workouts.workoutplandetail')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workoutplandetail',
            constraint=models.CheckConstraint(condition=models.Q(('order_number__gte', 1)), name='detail_order_min_1'),
        ),
        migrations.AddConstraint(
            model_name='workoutplandetail',
            constraint=models.CheckConstraint(condition=models.Q(('target_sets__gt', 0)), name='detail_sets_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutplandetail',
            constraint=models.CheckConstraint(condition=models.Q(('target_reps__gt', 0)), name='detail_reps_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutlog',
            constraint=models.CheckConstraint(condition=models.Q(('actual_sets__gt', 0)), name='log_sets_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutlog',
            constraint=models.CheckConstraint(condition=models.Q(('actual_reps__gt', 0)), name='log_reps_positive'),
        ),
    ]
