# Generated by Django 5.2.17 on 2026-10-03 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('body_fat_percent', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('recorded_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='health_weight_positive')],
            },
        ),
    ]
